### ISSUE TITLE
taxon() defaults

### ISSUE THREAD

**Issue by sckott** [zachary-foster/taxa2#2]
In https://github.com/zachary-foster/taxa2/blob/main/R/taxon.R#L112-L115 curious why name has `character()` while all other types have a `taxon_*()` type? As you know I copied your taxon function to make taxa_taxon in taxize, and was writing tests, testing pulling out parts of a `taxa_taxon` object and realized that `taxa2::tax_name` pulls out a character string, while all other tax_* functions pull out a vctrs object. Is that as planned? Or not?

**Comment by zachary-foster** [comment]
Yea, that was intentional. The others have some special feature that requires a new class: taxon_id has the database object, taxon_db can only accept some values, taxon_rank has ranks, etc. However, taxon name can really be anything, so I thought we would not gain much by making it a special class and just left it as character.

**Comment by sckott** [comment]
Sounds good 👌
